### ISSUE TITLE
What's behind the scenes?

### ISSUE THREAD

**Issue by hemulin** [chiaweilee/vue-nocaptcha#1]
Hi, thank you for this project.

I'm looking to see if there is any means of tracking associated with this captcha mechanism (for example like google is able to collect data from embedding its reCaptcha).

Couldn't find any information about the alibaba terms or even where `nc.js` & `nch5.js` comes from.

Can you shed some light on the flow of the captcha mechanism?

Thanks

**Comment by chiaweilee** [comment]
![2](https://user-images.githubusercontent.com/29817353/49495944-90f0f880-f89f-11e8-8bfc-58deb7e91b6f.png)

Oops! I never found a english version..
try translate this: https://help.aliyun.com/document_detail/66306.html?spm=5176.2020520162.0.0.6caa5fb0cQBzji

**Comment by hemulin** [comment]
Thank you.

The text seems to translate well and I understood the process of configuring a new NC.
The image, well, not. Can I ask for your "general" translation of its content in helping to understand which data do they collect by that captcha mechanism?
