### ISSUE TITLE
Oops... something's wrong. Please refresh and try again.(error:S9wiGg)

### ISSUE THREAD

**Issue by sureshvv** [chiaweilee/vue-nocaptcha#4]
I keep getting this error

**Comment by chiaweilee** [comment]
Several reasons for this problem..
Most of them is about the 'appkey', try another one.
By the way, it may also report 'something's wrong' under chrome's 'mobile dev mode'

**Comment by sureshvv** [comment]
I ended up using vue-recaptcha as described in 

https://itnext.io/how-to-use-google-recaptcha-with-vuejs-7756244400da

Works great!
